### ISSUE TITLE
Errors are aweful

### ISSUE THREAD

**Issue by FossPrime** [mhariri/docker-google-appengine-php#2] opened 2016-09-18 05:00 UTC
This is the out you would get for a syntax error

```
ERROR:root:php failure (255) with:
stdout:
Status: 500 Internal Server Error

X-Powered-By: PHP/5.5.37-2+deb.sury.org~xenial+1
Content-type: text/html


INFO     2016-09-18 04:57:20,977 module.py:788] default: "GET / HTTP/1.1" 500 -
```

Meanwhile the built in server would just out put what line the error is coming from. I'll need to get a VM up to check out the issue

**Comment by FossPrime** [comment] 2016-09-18 05:22
This is not a problem with the docker image, but the dev_appserver.py script it's self. Even with `--log_level=debug` it still doesn't transfer the errors, or save them. 

`--dev_appserver_log_level=debug` outputs a million messages, but not the ones from the php server instance. hum.

**Comment by mhariri** [comment] 2016-09-19 21:16
So I guess with your last comment, the issue is caused by dev_appserver.py itself. Closing it then.

**Closed as completed by mhariri** 2016-09-19 21:16 UTC
